apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion-search-frontend-deployment
  labels:
    app: motion-search-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion-search-frontend
  template:
    metadata:
      labels:
        app: motion-search-frontend
    spec:
      containers:
        - name: motion-search-frontend
          image: motion-search-frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: motion-search-frontend
spec:
  selector:
    app: motion-search-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: motion-search-frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   try_files $uri $uri/ /index.html;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - motion-search-frontend.lb.djnd.si
      secretName: motion-search-frontend-tls
  rules:
    - host: motion-search-frontend.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: motion-search-frontend
                port:
                  number: 80
