apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: motionsearch
resources:
  - frontend.yaml
  - backend.yaml
images:
  - name: motion-search-backend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-backend
    newTag: '774e469f328e564d50a0ed1489498838383996aa'
  - name: motion-search-frontend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-frontend
    newTag: '774e469f328e564d50a0ed1489498838383996aa'
