apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: motionsearch
resources:
  - frontend.yaml
  - backend.yaml
images:
  - name: motion-search-backend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-backend
    newTag: '5bad2a95a52298076846605da3b945e0b28987c1'
  - name: motion-search-frontend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-frontend
    newTag: '5bad2a95a52298076846605da3b945e0b28987c1'
