apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: motionsearch
resources:
  - frontend.yaml
  - backend.yaml
images:
  - name: motion-search-backend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-backend
    newTag: '016c1b4f67fea951d33ad1ca0c2753bc1cc57fd9'
  - name: motion-search-frontend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-frontend
    newTag: '016c1b4f67fea951d33ad1ca0c2753bc1cc57fd9'
