apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: motionsearch
resources:
  - frontend.yaml
  - backend.yaml
images:
  - name: motion-search-backend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-backend
    newTag: '5cd099ad5d11518a775979497e3b4d2f046b6a61'
  - name: motion-search-frontend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-frontend
    newTag: '5cd099ad5d11518a775979497e3b4d2f046b6a61'
