apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: motionsearch
resources:
  - frontend.yaml
  - backend.yaml
images:
  - name: motion-search-backend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-backend
    newTag: '9940368e3708af8b2c8fc88e0250acee0f7c74c5'
  - name: motion-search-frontend
    newName: rg.fr-par.scw.cloud/djnd/motion-search-frontend
    newTag: '9940368e3708af8b2c8fc88e0250acee0f7c74c5'
