
version: '3'

volumes:
  postgres-data:

services:
  backend:
    container_name: "backend"
    build: ./backend
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:changeme@db/motionsearch
      PYTHONPATH: /code:$PYTHONPATH
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: motionsearch
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
