# Generated by Django 3.2 on 2021-04-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motioncomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motion',
            name='age_range',
            field=models.ManyToManyField(blank=True, to='motions.MotionAgeRange'),
        ),
        migrations.AddField(
            model_name='motion',
            name='category',
            field=models.ManyToManyField(blank=True, to='motions.MotionCategory'),
        ),
        migrations.AddField(
            model_name='motion',
            name='debate_formats',
            field=models.ManyToManyField(blank=True, to='motions.DebateFormat'),
        ),
        migrations.AddField(
            model_name='motion',
            name='difficulties',
            field=models.ManyToManyField(blank=True, to='motions.MotionDifficulty'),
        ),
        migrations.AddField(
            model_name='motion',
            name='impro_prep',
            field=models.ManyToManyField(blank=True, to='motions.MotionImproPrep'),
        ),
        migrations.AddField(
            model_name='motion',
            name='info_text',
            field=models.ManyToManyField(blank=True, to='motions.MotionInfoText'),
        ),
        migrations.AddField(
            model_name='motion',
            name='links',
            field=models.ManyToManyField(blank=True, to='motions.MotionLink'),
        ),
        migrations.AddField(
            model_name='motion',
            name='training_focus',
            field=models.ManyToManyField(blank=True, to='motions.MotionTrainingFocus'),
        ),
        migrations.AddField(
            model_name='motion',
            name='type',
            field=models.ManyToManyField(blank=True, to='motions.MotionType'),
        ),
        migrations.AddField(
            model_name='motion',
            name='where_used',
            field=models.ManyToManyField(blank=True, to='motions.MotionWhereUsed'),
        ),
    ]
