# Generated by Django 3.2 on 2021-04-20 10:01

from django.db import migrations, models
import django.utils.timezone
import motions.models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='updated_at',
            field=motions.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='motion',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
