# Generated by Django 3.2 on 2021-04-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0004_remove_motion_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
