# Generated by Django 3.2 on 2021-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0005_alter_motion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioncategory',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
