# Generated by Django 3.2 on 2021-04-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0006_alter_motioncategory_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='difficulties',
        ),
        migrations.AddField(
            model_name='motion',
            name='difficulties',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.motiondifficulty'),
            preserve_default=False,
        ),
    ]
