# Generated by Django 3.2 on 2021-04-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0007_auto_20210428_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='age_range',
        ),
        migrations.AddField(
            model_name='motion',
            name='age_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.motionagerange'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='motion',
            name='debate_formats',
        ),
        migrations.AddField(
            model_name='motion',
            name='debate_formats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.debateformat'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='motion',
            name='impro_prep',
        ),
        migrations.AddField(
            model_name='motion',
            name='impro_prep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.motionimproprep'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='motion',
            name='training_focus',
        ),
        migrations.AddField(
            model_name='motion',
            name='training_focus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.motiontrainingfocus'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='motion',
            name='type',
        ),
        migrations.AddField(
            model_name='motion',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.motiontype'),
            preserve_default=False,
        ),
    ]
