# Generated by Django 3.2 on 2021-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0008_auto_20210428_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioninfotext',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
