# Generated by Django 3.2 on 2021-05-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0009_alter_motioninfotext_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioncomment',
            name='motion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motions.motion'),
            preserve_default=False,
        ),
    ]
