# Generated by Django 3.2 on 2021-05-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0010_alter_motioncomment_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='votes',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='motiondifficulty',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MotionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choices', models.PositiveSmallIntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'No vote')], default=3)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motions.motion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
