# Generated by Django 3.2 on 2021-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0012_alter_motionvote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioncomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
