# Generated by Django 3.2 on 2021-05-04 17:22

from django.db import migrations
import motions.models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0013_alter_motioncomment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioncomment',
            name='created_at',
            field=motions.models.AutoDateTimeField(auto_now=True),
        ),
    ]
