# Generated by Django 3.2 on 2021-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0016_alter_motionvote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionlink',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
