# Generated by Django 2.2.14 on 2021-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0018_motion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='motion',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='motions', to='motions.MotionCategory'),
        ),
        migrations.AddField(
            model_name='motion',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='motions', to='motions.MotionKeywords'),
        ),
    ]
