# Generated by Django 3.2 on 2021-05-04 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0012_alter_motionvote_user'),
        ('users', '0002_auto_20210504_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemotion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritemotion',
            unique_together={('user', 'motion')},
        ),
    ]
